### ISSUE TITLE
calcul du prix du montage d'un produit en fonction de son temps de montage (theorique ou effectif)

### ISSUE THREAD

**Issue by l3miage-tidjanma** [l3-miage-cl-ihm/projet-integrateur-2024-serveur-springboot-l3miage-aitelker#41]
source: [exemple de commande, paragraphe en bas. 1€/min](https://coda.io/d/l3miage-2324-pi-G05_dnwTuqy9-_S/Figures_su43-#Figures_tuURv/r19&view=modal)

**Comment by l3miage-campusb** [comment]
Pas besoin
